server:
  port: 8080

spring:
  application:
    name: card-api
  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:127.0.0.1:9042}
    local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER:datacenter1}
    keyspace-name: card_keyspace
    schema-action: create_if_not_exists
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  security:
    jwt:
      secret: ${JWT_SECRET:desafio_hyperativa_jwt_secret_key_super_secure_2026}
      expiration-ms: 86400000 # 24 hours
    crypto:
      aes-key: ${AES_KEY:1234567890123456} # 16 bytes = AES-128
      hmac-secret: ${HMAC_SECRET:desafio_hyperativa_hmac_secret_key_for_hashing_cards}
